### ISSUE TITLE
Initial DB migration fails

### ISSUE THREAD

**Issue by WardBenjamin** [Team254/cheesy-parts#20]
The first time you run `bundle exec rake db:migrate`, it fails with the following message: 

```>ubuntu@ip-172-31-94-160:~/vexu_parts$ bundle exec rake db:migrate
Warning: using Pathological, but no Pathfile was found.
rake aborted!
Sequel::MassAssignmentRestriction: method email= doesn't exist
/home/ubuntu/.rvm/gems/ruby-2.3.7/gems/sequel-4.31.0/lib/sequel/model/base.rb:2159:in `block in set_restricted'
/home/ubuntu/.rvm/gems/ruby-2.3.7/gems/sequel-4.31.0/lib/sequel/model/base.rb:2146:in `each'
/home/ubuntu/.rvm/gems/ruby-2.3.7/gems/sequel-4.31.0/lib/sequel/model/base.rb:2146:in `set_restricted'
/home/ubuntu/.rvm/gems/ruby-2.3.7/gems/sequel-4.31.0/lib/sequel/model/base.rb:1575:in `set'
/home/ubuntu/.rvm/gems/ruby-2.3.7/gems/sequel-4.31.0/lib/sequel/model/base.rb:2102:in `initialize_set'
/home/ubuntu/.rvm/gems/ruby-2.3.7/gems/sequel-4.31.0/lib/sequel/model/base.rb:1177:in `initialize'
db/migrations/011_add_starting_user.rb:7:in `new'
db/migrations/011_add_starting_user.rb:7:in `block (2 levels) in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.7/gems/sequel-4.31.0/lib/sequel/extensions/migration.rb:102:in `instance_eval'
/home/ubuntu/.rvm/gems/ruby-2.3.7/gems/sequel-4.31.0/lib/sequel/extensions/migration.rb:102:in `apply'
/home/ubuntu/.rvm/gems/ruby-2.3.7/gems/sequel-4.31.0/lib/sequel/extensions/migration.rb:538:in `block (2 levels) in run'
/home/ubuntu/.rvm/gems/ruby-2.3.7/gems/sequel-4.31.0/lib/sequel/extensions/migration.rb:468:in `checked_transaction'
/home/ubuntu/.rvm/gems/ruby-2.3.7/gems/sequel-4.31.0/lib/sequel/extensions/migration.rb:537:in `block in run'
/home/ubuntu/.rvm/gems/ruby-2.3.7/gems/sequel-4.31.0/lib/sequel/extensions/migration.rb:534:in `each'
/home/ubuntu/.rvm/gems/ruby-2.3.7/gems/sequel-4.31.0/lib/sequel/extensions/migration.rb:534:in `run'
/home/ubuntu/.rvm/gems/ruby-2.3.7/gems/sequel-4.31.0/lib/sequel/extensions/migration.rb:393:in `run'
/home/ubuntu/vexu_parts/Rakefile:16:in `block (2 levels) in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.3.7/bin/ruby_executable_hooks:15:in `eval'
/home/ubuntu/.rvm/gems/ruby-2.3.7/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

Subsequent tries results in a clean(er):

```ubuntu@ip-172-31-94-160:~/vexu_parts$ bundle exec rake db:migrate
Warning: using Pathological, but no Pathfile was found.``

Everything seems to work regardless, but I have only been able to repro this problem by re-running the migration on a new, clean database table.

**Comment by emmercm** [comment]
Seeing the same problem here, fresh MySQL instance. Running the command like this gets me past the problem:

```shell
bundle exec rake db:migrate || true
bundle exec rake db:migrate
```
